[build-system]
requires = [
    "setuptools>61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "avo-alarms"
dynamic = ["version"]
authors = [{name = "Aaron Wech", email = "awech@usgs.gov"}]
description = "Various volcano monitoring alarms."
readme = "README.md"
license = { text = "CC0-1.0" }
requires-python = ">=3.10"
dependencies = [
    "obspy",
    "pandas",
    "jinja2",
    "pyyaml",
    "cartopy"
]
classifiers = [
    # How mature is this project? Common values are
    #   3 - Alpha
    #   4 - Beta
    #   5 - Production/Stable
    "Development Status :: 4 - Beta",
    "Topic :: Scientific/Engineering",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: CC0 1.0 Universal (CC0 1.0)",
]
keywords = ["volcano", "geophysics", "monitoring"]

[project.scripts]
run-alarm = "avo_alarms.scripts.run_alarm:main"
email-test = "avo_alarms.scripts.email_test:main"
generic-alarm = "avo_alarms.scripts.generic_alarm:main"
update-metadata = "avo_alarms.scripts.update_metadata:main"
update-html = "avo_alarms.scripts.notification_html:main"

[tool.setuptools.dynamic]
version = {attr = "avo_alarms.__version__"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
avo_alarms = ["utils/alarms.mplstyle"]

[project.urls]
