alarm_type: Infrasound        # designates which alarm module will be imported and executed
alarm_name: SDPI Infrasound   # alarm name sent to icinga and in message alerts

# Infrasound channels list
nslc:
  - AV.SDPI.01.HDF
  - AV.SDPI.02.HDF
  - AV.SDPI.03.HDF
  - AV.SDPI.04.HDF
  - AV.SDPI.05.HDF
  - AV.SDPI.06.HDF

# Processing parameters
duration: 180         # duration value in seconds (3 * 60)
latency: 10.0         # seconds between timestamps and end of data window
taper: 5.0            # seconds to taper beginning and end of trace before filtering
f1: 1.0               # minimum frequency for bandpass filter
f2: 10.0              # maximum frequency for bandpass filter

# Detection parameters
min_cc: 0.6           # min normalized correlation coefficient to accept
min_chan: 3           # minimum number of channels for code to run
cc_shift_length: 6    # maximum seconds to shift in cross-correlation

# Alerting parameters
alert_memory: 3600     # lookback window (seconds)
max_alerts: 3          # max alerts within that window

# Infrasound target list:
# Required:
#   name, az_tolerance (degrees), min_pa (Pascals)
# Optional:
#   lat, lon, vmin (default 0.28 km/s), vmax (default 0.45 km/s)
#   seismic_nslc: is a list of seismic channels to be plot on detect
#   traveltime: boolean to determine whether to calculate predicted airwave traveltime
#
# lat/lon info taken from target list file set as environment variable,
# if `name` not listed there, lat/lon must be included here.

targets:
  - name: Pavlof
    az_tolerance: 8
    min_pa: 2.0
    seismic_nslc:
      - AV.PV6A..BDF
      - AV.PV6A..SHZ
      - AV.PN7A..BHZ
      - AV.PS4A..BHZ

  - name: Veniaminof
    az_tolerance: 6
    min_pa: 0.5
    seismic_nslc:
      - AV.VNSG..BHZ
      - AV.VNWF..BHZ
      - AV.VNCG..BHZ

  - name: Aniakchak
    az_tolerance: 3
    min_pa: 0.3
    seismic_nslc:
      - AV.ANPK..BHZ
      - AV.ANNW..BHZ
      - AV.BPPC..BHZ

  - name: Shishaldin
    az_tolerance: 5
    min_pa: 0.5
    seismic_nslc:
      - AV.SSBA..BHZ
      - AV.ISNN..BHZ
      - AV.WTUG..BHZ
