alarm_type: Magnitude
alarm_name: Earthquake Magnitude

magmin: 2.5           # minimum earthquake magnitude threshold
maxdep: 40            # maximum earthquake depth threshold
distance: 10          # maximum distance from any volcano in `VOLCANO_LIST`
duration: 7200        # lookback window (in seconds)

# mattermost_channel_id: special_channel_id_redirect

# mm_response_channels:
#   Aniakchak: volcano_channel_id_redirect
#   Edgecumbe: volcano_channel_id_redirect
#   Trident: volcano_channel_id_redirect
#   Katmai: volcano_channel_id_redirect
