alarm_type: NOAA_CIMSS
alarm_name: NOAA CIMSS

max_distance: 25      # maximum distance for sending an alert
# mattermost_channel_id: special_channel_id_redirect

# send alerts from elevated volcanoes to dedicated MM channel
elevated_volcano_dist: 20    # distance threshold in km
elevated_volcano_list:
  - Great Sitkin
  - Shishaldin
  - Kupreanof
# elevated_volcano_mm: special_channel_id_redirect

# send thermal alerts to dedicated MM channel
# thermal_alert_dist: 20       # distance threshold in km
# thermal_alerts_mm: special_channel_id_redirect
