############## Phonebook ###############
########################################
Johnny Volcano: phonenumber@sms.com
Dolly Lava:     phonenumber@sms.com
Ruby Caldera:   phonenumber@sms.com 
Duty Scientist: seriousnumber@mms.com
Bob:            mygmail@email.com