alarm_type: Tremor            # designates which alarm module will be imported and executed
alarm_name: Pavlof Tremor     # alarm name sent to icinga and in message alerts
volcano: Pavlof

# Station list
nslc:
  - AV.HAG..BHZ
  - AV.PS4A..BHZ
  - AV.PVV..BHZ
  - AV.PS1A..BHZ
  - AV.PN7A..BHZ
  - AV.PV6A..BHZ

# Alarm threshold parameters
duration: 3600             # [seconds] how far into past to look for detections
threshold: 25              # [minutes] required in past hour for notification
rsam_station: AV.PS1A..BHZ # N.S.L.C - channel to be used for RSAM threshold test
rsam_threshold: 180        # RSAM threshold for above nslc. Alarm won't send if below this level

# Alerting parameters
alert_memory: 3600     # lookback window (seconds)
max_alerts: 3          # max alerts within that window

# Waveform processing parameters
window_length: 300         # duration value in seconds (5 * 60)
latency: 10                # seconds between timestamps and end of data window
taper: 5                   # seconds to taper beginning and end of trace before filtering
f1: 1.0                    # minimum frequency for bandpass filter
f2: 6.0                    # maximum frequency for bandpass filter
highpass: 8.0
lowpass: 0.1

# Envelope location parameters
min_sta: 4                 # minimum number of stations for detection
Cmin: 0.5                  # minimum cross-correlation coefficient
Cmax: 0.95                 # maximum cross-correlation coefficient
bstrap: 10                 # number of bootstrap iterations
bstrap_prct: 0.04          # percentage of data to throw away in each iteration
max_scatter: 8.0           # maximum horizontal scatter in km

# Search grid definition (start/end/step; arrays built by the alarm code)
grid:
  lon_min: -162.22
  lon_max: -161.64
  lon_step: 0.02
  lat_min: 55.18
  lat_max: 55.56
  lat_step: 0.02
  depth_min: 1.0
  depth_max: 12.0
  depth_step: 0.2

phase_list:
  - 3kmps

# Supporting file locations. Optional. Defaults to tmp_files directory
# grid_file: Pavlof_tremor_grid.npz   # location of grid/model file
